apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: test-gitops-helm-ns
spec:
  targetNamespace: test-gitops-helm-ns
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: test-gitops-helm-ns
      version: "17.3.1"
  interval: 1m
  values:
    replicaCount: 1
    service:
      type: LoadBalancer

#kustomization.yaml:

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
